2021-11-05 06:42:52,375 INFO autoreload 9175 140161101076288 Watching for file changes with StatReloader
2021-11-05 06:43:22,594 WARNING log 9175 140160928700160 Not Found: /
2021-11-05 06:43:22,949 WARNING log 9175 140160928700160 Not Found: /favicon.ico
2021-11-05 06:43:25,840 ERROR log 9175 140160928700160 Internal Server Error: /manage/login/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 20, in import_string
    return getattr(module, class_name)
AttributeError: module 'utilities.context_processors' has no attribute 'settings'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 41, in _request_context_bind_template
    processors = template.engine.template_context_processors + self._processors
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/engine.py", line 85, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/engine.py", line 85, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 22, in import_string
    raise ImportError('Module "%s" does not define a "%s" attribute/class' % (
ImportError: Module "utilities.context_processors" does not define a "settings" attribute/class
2021-11-05 06:44:44,796 INFO autoreload 9175 140161101076288 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 06:44:45,250 INFO autoreload 9713 140321548166976 Watching for file changes with StatReloader
2021-11-05 06:44:47,266 ERROR log 9713 140321442813696 Internal Server Error: /manage/login/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
utilities.models.SiteSettings.DoesNotExist: SiteSettings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 162, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
2021-11-05 06:49:06,460 INFO autoreload 9713 140321548166976 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 06:49:06,989 INFO autoreload 10625 140132037883712 Watching for file changes with StatReloader
2021-11-05 06:49:23,870 INFO autoreload 10625 140132037883712 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:49:24,335 INFO autoreload 10759 140580099774272 Watching for file changes with StatReloader
2021-11-05 06:49:35,889 INFO autoreload 10759 140580099774272 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:49:36,358 INFO autoreload 10906 139834367649600 Watching for file changes with StatReloader
2021-11-05 06:53:06,850 INFO autoreload 10906 139834367649600 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:53:07,298 INFO autoreload 11287 140213010851648 Watching for file changes with StatReloader
2021-11-05 06:54:03,372 INFO autoreload 11287 140213010851648 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:54:03,808 INFO autoreload 11386 140138800863040 Watching for file changes with StatReloader
2021-11-05 06:54:29,273 ERROR log 11386 140138695509760 Internal Server Error: /manage/courses/category/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 161, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:38,153 ERROR log 11386 140138695509760 Internal Server Error: /manage/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 161, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:40,079 ERROR log 11386 140138695509760 Internal Server Error: /manage/utilities/sitesettings/1/change/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 763, in get_object
    return queryset.get(**{field.name: object_id})
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:43,509 ERROR log 11386 140138695509760 Internal Server Error: /manage/utilities/sitesettings/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:46,799 ERROR log 11386 140138695509760 Internal Server Error: /manage/utilities/sitesettings/add/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 161, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:51,926 ERROR log 11386 140138695509760 Internal Server Error: /manage/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 161, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:53,776 ERROR log 11386 140138695509760 Internal Server Error: /manage/
Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: utilities_sitesettings.cookies_status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/home/shosen/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/home/shosen/projects/shosen_lms/utilities/context_processors.py", line 5, in site_settings
    return {'site_settings': SiteSettings.load()}
  File "/home/shosen/projects/shosen_lms/utilities/models.py", line 161, in load
    obj, created = cls.objects.get_or_create(pk=1)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/shosen/projects/shosen_lms/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: utilities_sitesettings.cookies_status
2021-11-05 06:54:59,331 INFO autoreload 11386 140138800863040 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:54:59,849 INFO autoreload 11776 139660855068480 Watching for file changes with StatReloader
2021-11-05 06:57:35,352 INFO autoreload 11776 139660855068480 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:57:35,870 INFO autoreload 12120 139892004927296 Watching for file changes with StatReloader
2021-11-05 06:58:36,489 INFO autoreload 12120 139892004927296 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 06:58:36,926 INFO autoreload 12214 140607306401600 Watching for file changes with StatReloader
2021-11-05 07:02:02,736 INFO autoreload 12214 140607306401600 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:02:03,208 INFO autoreload 12568 139911583885120 Watching for file changes with StatReloader
2021-11-05 07:02:17,957 INFO autoreload 12568 139911583885120 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:02:18,421 INFO autoreload 12687 139630514202432 Watching for file changes with StatReloader
2021-11-05 07:02:24,849 INFO autoreload 12687 139630514202432 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:02:25,307 INFO autoreload 12779 140096946546496 Watching for file changes with StatReloader
2021-11-05 07:02:29,675 INFO autoreload 12779 140096946546496 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:02:30,120 INFO autoreload 12861 140665926801216 Watching for file changes with StatReloader
2021-11-05 07:03:11,745 INFO autoreload 12861 140665926801216 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:03:12,201 INFO autoreload 13028 139925993994048 Watching for file changes with StatReloader
2021-11-05 07:03:40,368 INFO autoreload 13028 139925993994048 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:03:40,814 INFO autoreload 13180 139980450883392 Watching for file changes with StatReloader
2021-11-05 07:03:51,302 INFO autoreload 13180 139980450883392 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:03:51,789 INFO autoreload 13291 140075209942848 Watching for file changes with StatReloader
2021-11-05 07:05:02,570 INFO autoreload 13291 140075209942848 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:05:03,029 INFO autoreload 13610 140392084256576 Watching for file changes with StatReloader
2021-11-05 07:05:06,402 INFO autoreload 13610 140392084256576 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:05:06,871 INFO autoreload 13661 140080886458176 Watching for file changes with StatReloader
2021-11-05 07:05:13,315 INFO autoreload 13661 140080886458176 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:05:13,784 INFO autoreload 13730 140086761703232 Watching for file changes with StatReloader
2021-11-05 07:05:53,454 INFO autoreload 13730 140086761703232 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:05:53,931 INFO autoreload 13886 139729480435520 Watching for file changes with StatReloader
2021-11-05 07:05:58,292 INFO autoreload 13886 139729480435520 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:05:58,753 INFO autoreload 13965 140465517590336 Watching for file changes with StatReloader
2021-11-05 07:15:21,838 INFO autoreload 13965 140465517590336 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:15:22,476 INFO autoreload 15345 139850000160576 Watching for file changes with StatReloader
2021-11-05 07:15:43,572 INFO autoreload 15345 139850000160576 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:15:44,163 INFO autoreload 15427 139745675757376 Watching for file changes with StatReloader
2021-11-05 07:16:26,927 INFO autoreload 15427 139745675757376 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:16:27,508 INFO autoreload 15515 139972880774976 Watching for file changes with StatReloader
2021-11-05 07:17:07,381 INFO autoreload 15515 139972880774976 /home/shosen/projects/shosen_lms/lms/urls.py changed, reloading.
2021-11-05 07:17:07,982 INFO autoreload 15636 140374169573184 Watching for file changes with StatReloader
2021-11-05 07:17:11,323 INFO autoreload 15636 140374169573184 /home/shosen/projects/shosen_lms/lms/urls.py changed, reloading.
2021-11-05 07:17:11,945 INFO autoreload 15680 140033685063488 Watching for file changes with StatReloader
2021-11-05 07:18:02,068 INFO autoreload 15841 140614382577472 Watching for file changes with StatReloader
2021-11-05 07:20:24,765 INFO autoreload 15841 140614382577472 /home/shosen/projects/shosen_lms/lms/urls.py changed, reloading.
2021-11-05 07:20:25,482 INFO autoreload 16278 139658947143488 Watching for file changes with StatReloader
2021-11-05 07:26:33,953 INFO autoreload 16278 139658947143488 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:26:34,550 INFO autoreload 16901 139765346187072 Watching for file changes with StatReloader
2021-11-05 07:27:51,892 INFO autoreload 16901 139765346187072 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:27:52,493 INFO autoreload 16995 139684847171392 Watching for file changes with StatReloader
2021-11-05 07:29:43,481 INFO autoreload 16995 139684847171392 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:29:44,082 INFO autoreload 17145 139930222434112 Watching for file changes with StatReloader
2021-11-05 07:30:03,079 INFO autoreload 17145 139930222434112 /home/shosen/projects/shosen_lms/utilities/models.py changed, reloading.
2021-11-05 07:30:03,698 INFO autoreload 17237 140555249727296 Watching for file changes with StatReloader
2021-11-05 07:30:35,074 INFO autoreload 17237 140555249727296 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:30:35,694 INFO autoreload 17395 139703575033664 Watching for file changes with StatReloader
2021-11-05 07:30:41,198 INFO autoreload 17395 139703575033664 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:30:41,834 INFO autoreload 17477 140478666807104 Watching for file changes with StatReloader
2021-11-05 07:30:59,747 INFO autoreload 17477 140478666807104 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:31:00,365 INFO autoreload 17590 139926160643904 Watching for file changes with StatReloader
2021-11-05 07:32:18,602 INFO autoreload 17590 139926160643904 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:32:19,217 INFO autoreload 17925 140568133211968 Watching for file changes with StatReloader
2021-11-05 07:32:31,986 INFO autoreload 17925 140568133211968 /home/shosen/projects/shosen_lms/utilities/admin.py changed, reloading.
2021-11-05 07:32:32,588 INFO autoreload 18041 139814748411712 Watching for file changes with StatReloader
2021-11-05 07:34:03,167 INFO autoreload 18041 139814748411712 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:34:03,833 INFO autoreload 18536 140343843456832 Watching for file changes with StatReloader
2021-11-05 07:37:45,046 INFO autoreload 18536 140343843456832 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:37:45,729 INFO autoreload 19319 139827326523200 Watching for file changes with StatReloader
2021-11-05 07:37:55,257 INFO autoreload 19319 139827326523200 /home/shosen/projects/shosen_lms/lms/settings.py changed, reloading.
2021-11-05 07:37:55,843 INFO autoreload 19381 139786087667520 Watching for file changes with StatReloader
